# Run with:
# cargo make docs
# cargo make doc-katex
[tasks.doc-katex]
env = { "RUSTDOCFLAGS" = "--html-in-header katex-header.html" }
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.all]
dependencies = [
    "docs",
    "doc-katex",
]

